import fs from 'fs/promises';
import path from 'path';
import type { GroceryItem } from './data';
import type { ImagePlaceholder } from './placeholder-images';
import { generateDynamicPlaceholder } from './placeholder-utils';

function getKeywordsFromCategory(category: string): string {
    const categoryKeywords: { [key: string]: string } = {
        'delicatessen & eggs': 'delicatessen egg',
        'asian deli': 'asian deli',
        'noodles': 'noodles',
        'cooking sauces & gravy': 'sauce gravy',
        'soy & asian sauces': 'soy sauce',
        'oil & seasoning & sauce': 'oil seasoning',
        'fruits & vegetable local': 'vegetable fruit',
        'local vegetable': 'vegetable',
        'jam honey & spreads': 'jam honey',
        'jams & marmalades': 'jam marmalade',
        'health & beauty': 'health beauty',
        'dental care': 'dental care',
        'pet & household': 'pet household',
        'toys': 'toys',
        'dolls': 'doll',
        'beer wine & spirits': 'beer wine',
        'red wine': 'red wine',
        'bakery': 'bakery',
        'thai confectionery': 'thai dessert',
        'baby & adult care': 'baby care',
        'baby diapers': 'diaper',
        'drinks': 'drink',
        'uht & canned milk': 'uht milk',
        'fresh produce': 'fresh produce',
        'local fruit': 'fruit',
        'cut fruit': 'cut fruit',
        'condiments & dressings': 'condiment dressing',
        'herbs spices & paste': 'herb spice',
        'hot beverages': 'hot beverage',
        'coffee': 'coffee',
        'crisps & snacks': 'crisps snack',
        'savoury snacks': 'savoury snack',
        'nuts & dried fruits': 'nuts fruit',
        'dried fruit': 'dried fruit',
        'body & facial skincare': 'skincare',
        'facial care': 'facial care',
        'butcher shop': 'meat',
        'pork': 'pork',
        'pork various': 'pork',
        'soft drinks': 'soft drink',
        'rtd coffee & tea': 'rtd coffee',
        'desserts & fruit': 'dessert fruit',
        'frozen fruit': 'frozen fruit',
        'sausage & bacon': 'sausage bacon',
        'meat & chicken': 'meat chicken',
        'bacon': 'bacon',
        'deli meats': 'deli meat',
        'ham & bacon': 'ham bacon',
        'salmon & seafood': 'salmon seafood',
        'other seafood': 'seafood',
        'fish & seafood': 'fish seafood',
        'prawns & seafood': 'prawn seafood',
        'rice & pasta & beans': 'rice pasta',
        'pasta': 'pasta',
        'milk & cream': 'milk cream',
        'cream': 'cream',
        'yogurts': 'yogurt',
        'cheese': 'cheese',
        'block': 'cheese',
        'beer & cider': 'beer cider',
        'import beer': 'import beer',
        'spirits & liqueurs': 'spirit liqueur',
        'gin vodka & tequila': 'gin vodka',
        'ice cream & ice': 'ice cream',
        'tubs': 'ice cream',
        'household': 'household',
        'tissues & napkins': 'tissue napkin',
        'breakfast cereal': 'cereal',
        'muesli & oats': 'muesli oat',
        'canned meat': 'canned meat',
        'thai snacks': 'thai snack',
        'rice': 'rice',
        'cakes & pastries': 'cake pastry',
        'cookies': 'cookie',
        'bread': 'bread',
        'specialty': 'specialty bread',
        'hba': 'hba',
        'skin care': 'skin care',
        'hair care': 'hair care',
        'shampoo': 'shampoo',
        'pet supplies': 'pet supply',
        'dog': 'dog',
        'cat': 'cat',
        'houseware': 'houseware',
        'kitchenware': 'kitchenware',
        'electrical': 'electrical',
        'paper products': 'paper product',
        'laundry': 'laundry',
        'cleaning': 'cleaning',
        'air freshener': 'air freshener',
        'insecticides': 'insecticide',
        'seasonal': 'seasonal',
        'x\'mas': 'christmas',
        'hamper': 'hamper',
        'gift basket': 'gift basket',
        'other': 'other',
        'international foods': 'international food',
        'prepared food': 'prepared food',
        'local foods': 'local food',
        'antipasti': 'antipasto',
        'salami': 'salami',
        'olives': 'olive',
        'dips & pate': 'dip pate',
        'pate & terrine': 'pate terrine',
        'ready meals': 'ready meal',
        'sandwiches pitas & bread': 'sandwich bread',
        'soup & salads': 'soup salad',
        'western': 'western food',
        'mexican': 'mexican food',
        'pies & sausage rolls': 'pie sausage',
        'pies': 'pie',
        'entrees & snacks': 'entree snack',
        'desserts': 'dessert',
        'vegan & vegetarian': 'vegan vegetarian',
        'meat alternatives': 'meat alternative',
        'pizza & garlic bread': 'pizza bread',
        'traditional': 'traditional pizza',
        'gourmet': 'gourmet',
        'import vegetables': 'import vegetable',
        'mushrooms & tomatoes': 'mushroom tomato',
        'salads & herbs': 'salad herb',
        'roots': 'root vegetable',
        'leafs': 'leafy green',
        'organic': 'organic',
        'import': 'import',
        'local': 'local',
        'best value import': 'import',
        'super steak': 'steak',
        'thai french beef': 'thai beef',
        'australian beef': 'australian beef',
        'n.z beef': 'nz beef',
        'u.s.a beef': 'usa beef',
        'japan beef': 'japan beef',
        'pork cuts': 'pork cut',
        'cp kurobuta pork': 'kurobuta pork',
        'sausages': 'sausage',
        'frozen sausages': 'frozen sausage',
        'local sausage': 'local sausage',
        'cold cuts': 'cold cut',
        'continental & cured': 'cured meat',
        'ham': 'ham',
        'smoked seafood': 'smoked seafood',
        'mollusks': 'mollusk',
        'crustacean': 'crustacean',
        'fish fillets': 'fish fillet',
        'local seafood': 'local seafood',
        'fresh flowers': 'flower',
        'vegetables': 'vegetable',
        'fruits': 'fruit',
        'import fruit': 'import fruit',
        'avocado & others': 'avocado',
        'apples & pears': 'apple pear',
        'stone fruit': 'stone fruit',
        'citrus': 'citrus',
        'berries': 'berry',
        'grapes': 'grape',
        'melon': 'melon',
        'bread category': 'bread',
        'multigrain & wholewheat': 'wholewheat bread',
        'baguettes': 'baguette',
        'regular': 'bread',
        'cookie and confectionery': 'cookie confectionery',
        'pasty category': 'pastry',
        'season category': 'seasonal',
        'cake category': 'cake',
        'croissants': 'croissant',
        'flavoured': 'croissant',
        'plain greek & natural': 'greek yogurt',
        'drinking yoghurt': 'drinking yogurt',
        'cream cottage & ricotta': 'cottage cheese',
        'parmesan & italian': 'parmesan',
        'cheddar cheese': 'cheddar',
        'swiss cheese': 'swiss cheese',
        'brie cheese': 'brie',
        'camembert': 'camembert',
        'edam': 'edam',
        'feta & goat\'s cheese': 'feta cheese',
        'goat cheese': 'goat cheese',
        'blue cheese': 'blue cheese',
        'cream & cottage cheese': 'cream cheese',
        'cheese spread & snacks': 'cheese spread',
        'snack cheese': 'snack cheese',
        'uht milk': 'uht milk',
        'plain milk': 'plain milk',
        'alternative milk': 'alternative milk',
        'butter & margarine': 'butter margarine',
        'butter salted': 'salted butter',
        'butter unsalted': 'unsalted butter',
        'butter': 'butter',
        'margarine': 'margarine',
        'flavouring essence & food color': 'food coloring',
        'sugar & sweeteners': 'sugar sweetener',
        'yeast & baking ingredients': 'yeast baking',
        'flour': 'flour',
        'cooking chocolate & cocoa': 'cocoa',
        'baking needs': 'baking need',
        'canned vegetables': 'canned vegetable',
        'canned fruits': 'canned fruit',
        'canned fish': 'canned fish',
        'canned meat & meals': 'canned meat',
        'canned soup': 'canned soup',
        'canned beans': 'canned bean',
        'canned tomatoes': 'canned tomato',
        'vinegars': 'vinegar',
        'cooking oils': 'cooking oil',
        'salad dressings': 'salad dressing',
        'mustard': 'mustard',
        'chilli & hot sauce': 'hot sauce',
        'tomato & bbq sauce': 'bbq sauce',
        'bottled sauces': 'bottled sauce',
        'cooking pastes': 'cooking paste',
        'gravy & stocks': 'gravy stock',
        'salt & pepper': 'salt pepper',
        'spaghetti': 'spaghetti',
        'macaroni': 'macaroni',
        'vermicelli': 'vermicelli',
        'fusilli': 'fusilli',
        'penne': 'penne',
        'lasagne & cannelloni': 'lasagne',
        'gnocchi': 'gnocchi',
        'linguine': 'linguine',
        'fettuccine & tagliatelle': 'fettuccine',
        'other pasta': 'pasta',
        'white wine': 'white wine',
        'new zealand': 'nz wine',
        'australia': 'au wine',
        'france': 'fr wine',
        'italy': 'it wine',
        'usa': 'us wine',
        'chile': 'cl wine',
        'spain': 'es wine',
        'germany': 'de wine',
        'argentina': 'ar wine',
        'south africa': 'za wine',
        'portugal': 'pt wine',
        'other regions': 'wine',
        'champagne & sparkling wine': 'champagne',
        'liqueurs': 'liqueur',
        'sake': 'sake',
        'soju': 'soju',
        'other spirits': 'spirit',
        'whisky rum & brandy': 'whisky rum',
        'thai whisky': 'thai whisky',
        'whisky single malt': 'single malt',
        'bourbon': 'bourbon',
        'brandy': 'brandy',
        'rum': 'rum',
        'gin': 'gin',
        'vodka': 'vodka',
        'tequila': 'tequila',
        'aperitif': 'aperitif',
        'bitter': 'bitter',
        'local beer': 'local beer',
        'water & mineral water': 'water',
        'still water': 'still water',
        'sparkling water': 'sparkling water',
        'local soft drinks': 'soft drink',
        'imported soft drinks': 'soft drink',
        'cola': 'cola',
        'natural': 'natural drink',
        'sparkling': 'sparkling drink',
        'energy drink': 'energy drink',
        'sports drink': 'sport drink',
        'health drinks': 'health drink',
        'juices': 'juice',
        'fruit juice': 'fruit juice',
        'juice local': 'local juice',
        'juice import': 'import juice',
        'fresh juices': 'fresh juice',
        'syrups & cordials': 'syrup cordial',
        'syrups': 'syrup',
        'cordials': 'cordial',
        'tea': 'tea',
        'tonic cocoa & chocolate': 'tonic cocoa',
        'cocoa/tea/coffee': 'coffee tea',
        'cereal / muesli': 'cereal muesli',
        'cereals': 'cereal',
        'breakfast bars': 'breakfast bar',
        'honey / syrups': 'honey syrup',
        'other spreads': 'spread',
        'peanut butter': 'peanut butter',
        'chocolate': 'chocolate',
        'sharing & gifts': 'gift chocolate',
        'bars': 'chocolate bar',
        'candies & marshmallows': 'candy marshmallow',
        'gums & mints': 'gum mint',
        'potato chips': 'potato chip',
        'seafood & seaweed': 'seafood snack',
        'jerky & meat': 'jerky meat',
        'popcorn': 'popcorn',
        'crackers & savoury': 'cracker',
        'sweet biscuits': 'biscuit',
        'superfoods': 'superfood',
        'energy & sports supplements': 'energy supplement',
        'protein bars': 'protein bar',
        'other supplements': 'supplement',
        'bath shower & soap': 'bath soap',
        'shower & body wash': 'body wash',
        'body care': 'body care',
        'wet tissues & wipes': 'wet wipe',
        'tools & accessories': 'accessory',
        'toothbrushes': 'toothbrush',
        'floss & mouthwash': 'mouthwash',
        'toothpaste': 'toothpaste',
        'hair removal': 'hair removal',
        'blades & razors': 'razor',
        'shaving gels & foams': 'shaving foam',
        'deodorants': 'deodorant',
        'deodorants & talcum': 'deodorant talcum',
        'conditioner': 'conditioner',
        'hair treatment': 'hair treatment',
        'hair styling': 'hair styling',
        'face': 'face makeup',
        'lips': 'lipstick',
        'eyes': 'eye makeup',
        'accessories': 'accessory',
        'tools': 'tool',
        'hair': 'hair accessory',
        'baby needs': 'baby need',
        'tissues': 'tissue',
        'cleaning tools': 'cleaning tool',
        'stationery': 'stationery',
        'writing instruments': 'pen pencil',
        'card': 'card',
        'souvenir': 'souvenir',
        'religion': 'religion',
        'plastic': 'plastic bag',
        'paper': 'paper',
        'outdoor & hardware': 'outdoor hardware',
        'bbq & outdoor': 'bbq outdoor',
    };

    const lowerCategory = category.toLowerCase();
    return categoryKeywords[lowerCategory] || lowerCategory.split('&')[0].trim();
}

export async function generatePlaceholderImages(items: GroceryItem[]) {
  const placeholderImages: ImagePlaceholder[] = items.map((item) => {
    const imageHint = getKeywordsFromCategory(item.category);
    // Use dynamic SVG placeholder that generates instant, fast-loading images
    // No external URLs - generates data URIs with diverse patterns and colors
    const imageUrl = generateDynamicPlaceholder(item.name, item.category, 400, 300);
    return {
      id: `grocery-${item.id}`,
      description: item.name,
      imageUrl: imageUrl,
      imageHint: imageHint,
    };
  });

  const jsonContent = JSON.stringify({ placeholderImages }, null, 2);
  const filePath = path.join(process.cwd(), 'src', 'lib', 'placeholder-images.json');
  
  try {
    await fs.writeFile(filePath, jsonContent, 'utf-8');
  } catch (error) {
    console.error('Failed to write placeholder images:', error);
  }
}
